import assert from "node:assert/strict";
import { readdir, readFile } from "node:fs/promises";
import { test } from "node:test";

const installHtml = await readFile(new URL("./install.html", import.meta.url), "utf8");
const installJs = await readFile(new URL("./install.js", import.meta.url), "utf8");
const indexHtml = await readFile(new URL("./index.html", import.meta.url), "utf8");
const appJs = await readFile(new URL("./app.js", import.meta.url), "utf8");
const settingsHtml = await readFile(new URL("./settings.html", import.meta.url), "utf8");
const settingsJs = await readFile(new URL("./settings.js", import.meta.url), "utf8");
const workerHtml = await readFile(new URL("./worker.html", import.meta.url), "utf8");
const workerErrorHtml = await readFile(new URL("./worker-error.html", import.meta.url), "utf8");
const workerJs = await readFile(new URL("./worker.js", import.meta.url), "utf8");
const styleCss = await readFile(new URL("./style.css", import.meta.url), "utf8");
const marketplaceFiles = await readdir(new URL(".", import.meta.url));
const expectedMarketplaceFiles = [
  "app.js",
  "index.html",
  "install.css",
  "install.html",
  "install.js",
  "marketplace.test.js",
  "settings.html",
  "settings.js",
  "style.css",
  "worker-error.html",
  "worker.html",
  "worker.js",
];

test("marketplace archive has static Bitrix24 entry files", () => {
  assert.match(installHtml, /install\.css/);
  assert.match(installHtml, /install\.js/);
  assert.match(indexHtml, /style\.css/);
  assert.match(indexHtml, /app\.js/);
  assert.match(settingsHtml, /settings\.js\?v=layout-20260814-7/);
  assert.match(settingsHtml, /style\.css\?v=layout-20260814-7/);
  assert.match(indexHtml, /app\.js\?v=layout-20260814-7/);
  assert.match(indexHtml, /style\.css\?v=layout-20260814-7/);
  assert.match(workerHtml, /worker\.js\?v=layout-20260814-7/);
  assert.match(indexHtml, /Deal Invoice Summary v\.25 Marketplace B24/);
  assert.match(installHtml, /api\.bitrix24\.com\/api\/v1/);
  assert.match(indexHtml, /api\.bitrix24\.com\/api\/v1/);
  assert.match(settingsHtml, /api\.bitrix24\.com\/api\/v1/);
  assert.match(settingsHtml, /loader_9_no7zeu\.js/);
  assert.doesNotMatch(indexHtml, /loader_9_no7zeu\.js/);
  assert.match(workerHtml, /api\.bitrix24\.com\/api\/v1/);
  assert.match(workerErrorHtml, /OK/);
});

test("marketplace runtime package stays serverless", () => {
  assert.deepEqual([...marketplaceFiles].sort(), expectedMarketplaceFiles);
  const runtimeFiles = marketplaceFiles.filter((file) => file !== "marketplace.test.js");
  assert.deepEqual(runtimeFiles.sort(), ["app.js", "index.html", "install.css", "install.html", "install.js", "settings.html", "settings.js", "style.css", "worker-error.html", "worker.html", "worker.js"]);
});

test("marketplace installer cleans old left menu, binds background worker, and completes install", () => {
  assert.match(installJs, /placement\.bind/);
  assert.match(installJs, /LEFT_MENU/);
  assert.match(installJs, /left-menu-cleanup/);
  assert.match(installJs, /skippedBind: true/);
  assert.match(installJs, /unbindPlacementAll\("LEFT_MENU", 10\)/);
  assert.match(installJs, /основной пункт создаётся настройкой версии Marketplace/);
  assert.doesNotMatch(installJs, /PLACEMENT: "LEFT_MENU"/);
  assert.match(installJs, /PAGE_BACKGROUND_WORKER/);
  assert.match(installJs, /worker\.html/);
  assert.match(installJs, /worker-error\.html/);
  assert.match(installJs, /crm\.category\.list/);
  assert.match(installJs, /dealInvoiceSummaryDealCategories/);
  assert.match(installJs, /function cacheDealCategories/);
  assert.match(installJs, /crm\.deal\.userfield\.add/);
  assert.match(installJs, /crm\.deal\.userfield\.update/);
  assert.match(installJs, /dealInvoiceSummarySettings/);
  assert.match(installJs, /dealInvoiceSummaryDefaultSetupVersion/);
  assert.match(installJs, /calculationCategoryId:\s*"all"/);
  assert.match(installJs, /function configureDealCardSection/);
  assert.match(installJs, /DEFAULT_SETTINGS/);
  assert.match(installJs, /default-fields-and-mapping/);
  assert.match(installJs, /Стандартные поля и сопоставление сохранены для всех пользователей и всех доступных воронок/);
  assert.match(installJs, /\[\{ id: 0, name: "Основная" \}, \.\.\.categories\]/);
  assert.match(installJs, /placement\.unbind/);
  assert.match(installJs, /function bindPlacement/);
  assert.match(installJs, /function unbindPlacementAll/);
  assert.match(installJs, /maxAttempts = 5/);
  assert.match(installJs, /function isPlacementMaxCountError/);
  assert.match(installJs, /errorHandlerUrl/);
  assert.match(installJs, /ERROR_PLACEMENT_MAX_COUNT/);
  assert.match(installJs, /Placement max count/);
  assert.doesNotMatch(installJs, /CRM_DEAL_DETAIL_TAB/);
  assert.match(installJs, /BX24\.installFinish/);
  assert.match(installJs, /INSTALL_STEP_DELAY_MS = 2500/);
  assert.match(installJs, /logNode\.textContent \+=/);
  assert.match(installJs, /await wait\(INSTALL_STEP_DELAY_MS\)/);
});

test("marketplace app uses Bitrix24 REST directly without VibeCode backend", () => {
  assert.match(appJs, /crm\.deal\.get/);
  assert.match(appJs, /crm\.deal\.list/);
  assert.match(appJs, /crm\.item\.list/);
  assert.match(appJs, /crm\.deal\.update/);
  assert.match(appJs, /crm\.deal\.userfield\.add/);
  assert.match(appJs, /crm\.deal\.userfield\.update/);
  assert.match(appJs, /crm\.deal\.details\.configuration\.get/);
  assert.match(appJs, /crm\.deal\.details\.configuration\.set/);
  assert.match(appJs, /crm\.item\.details\.configuration\.get/);
  assert.match(appJs, /crm\.item\.details\.configuration\.set/);
  assert.match(appJs, /crm\.category\.list/);
  assert.match(appJs, /dealCategoryId/);
  assert.match(appJs, /updatedCategories/);
  assert.match(appJs, /isEmptyCardLayoutError/);
  assert.match(appJs, /createdFromDefaultLayout/);
  assert.match(appJs, /deal_invoice_summary/);
  assert.match(appJs, /function defaultDealCardLayout/);
  assert.match(appJs, /defaultFieldLabels/);
  assert.match(appJs, /function localizedLabel/);
  assert.match(appJs, /function firstHumanLabel/);
  assert.match(appJs, /function isSymbolicFieldLabel/);
  assert.match(appJs, /const userLabel = userFieldLabels\.get\(normalizedId\)/);
  assert.match(appJs, /function readableFieldType/);
  assert.match(appJs, /function uniqueHumanLabel/);
  assert.match(appJs, /function canManageCrmSettings/);
  assert.match(appJs, /callMethod\("user\.admin"\)/);
  assert.match(appJs, /function setMappingAccess/);
  assert.match(appJs, /CRM admin rights required/);
  assert.match(appJs, /Сопоставление доступно только администратору\./);
  assert.match(appJs, /function ensureDefaultSetupIfNeeded/);
  assert.match(appJs, /dealInvoiceSummaryDefaultSetupVersion/);
  assert.match(appJs, /setupVersion === runtimeVersion/);
  assert.match(appJs, /standardFieldsExist/);
  assert.match(appJs, /calculationCategoryId: "all"/);
  assert.match(appJs, /Стандартные поля и сопоставление настроены для всех воронок/);
  assert.match(appJs, /LANG_EDIT_FORM_LABEL/);
  assert.match(appJs, /Array\.isArray\(value\)/);
  assert.match(appJs, /if \(defaultLabel\) return defaultLabel/);
  assert.match(appJs, /layout-20260814-7/);
  assert.match(appJs, /Deal Invoice Summary v\.25 Marketplace B24/);
  assert.match(appJs, /operation: "manual-recalculate"/);
  assert.match(appJs, /operation: "ensure-fields"/);
  assert.match(appJs, /operation: "save-mapping"/);
  assert.match(appJs, /\^ufCrm\[A-Z0-9\]/);
  assert.match(appJs, /Сумма выставленных счетов/);
  assert.doesNotMatch(appJs, /vibecode\.bitrix24\.tech/);
  assert.doesNotMatch(appJs, /\/api\/recalculate/);
});

test("marketplace background worker watches open deal pages without backend", () => {
  assert.match(workerJs, /layout-20260814-7/);
  assert.match(workerJs, /Deal Invoice Summary v\.25 Marketplace B24/);
  assert.match(workerJs, /BX24\?\.placement\?\.info/);
  assert.match(workerJs, /PLACEMENT_OPTIONS/);
  assert.match(workerJs, /PAGE_BACKGROUND_WORKER/);
  assert.match(workerJs, /crm\\\/deal\\\/details\\\/\(\\d\+\)/);
  assert.match(workerJs, /crm\.deal\.get/);
  assert.match(workerJs, /crm\.item\.list/);
  assert.match(workerJs, /crm\.deal\.update/);
  assert.match(workerJs, /dealInvoiceSummarySettings/);
  assert.match(workerJs, /function parseSettingsPayload/);
  assert.match(workerJs, /calculationCategoryId/);
  assert.match(workerJs, /function dealMatchesCalculationCategory/);
  assert.match(workerJs, /skippedCategory: true/);
  assert.match(workerJs, /dealInvoiceSummaryWorkerStatus/);
  assert.match(workerJs, /workerPollIntervalMs = 5000/);
  assert.match(workerJs, /workerStatusThrottleMs = 60000/);
  assert.match(workerJs, /background-open-recalculate/);
  assert.match(workerJs, /background-deal-change-recalculate/);
  assert.match(workerJs, /background-deal-list-start/);
  assert.match(workerJs, /background-deal-list-baseline/);
  assert.match(workerJs, /background-deal-list-change-recalculate/);
  assert.match(workerJs, /crm\.deal\.list/);
  assert.match(workerJs, /DATE_MODIFY/);
  assert.match(workerJs, /listMonitorLimit = 25/);
  assert.match(workerJs, /function checkRecentDealChanges/);
  assert.match(workerJs, /function isDealWorkspaceUri/);
  assert.match(workerJs, /crm\\\/deal/);
  assert.match(workerJs, /OPPORTUNITY \?\? deal\.opportunity/);
  assert.match(workerJs, /STAGE_ID \|\| deal\.stageId/);
  assert.match(workerJs, /reloadData/);
  assert.match(workerJs, /BX24\.reloadWindow/);
  assert.doesNotMatch(workerJs, /vibecode\.bitrix24\.tech/);
  assert.doesNotMatch(workerJs, /\/api\/recalculate/);
});

test("marketplace report resolves invoice stages and assigned users", () => {
  assert.match(appJs, /crm\.item\.stage\.list/);
  assert.match(appJs, /crm\.status\.list/);
  assert.match(appJs, /stageLookup: stageDiagnostics/);
  assert.match(appJs, /STATUS_ID: stageId/);
  assert.match(appJs, /callList\("crm\.item\.stage\.list", \{ entityTypeId: 31 \}, "stages"\)/);
  assert.match(appJs, /SMART_INVOICE_STAGE_/);
  assert.match(appJs, /DYNAMIC_31_STAGE_/);
  assert.match(appJs, /__stagePrefix/);
  assert.match(appJs, /crm\.status\.entity\.types/);
  assert.match(appJs, /\?:DYNAMIC_31_STAGE\|SMART_INVOICE_STAGE/);
  assert.match(appJs, /stage\?\.statusId \|\| stage\?\.STATUS_ID \|\| stage\?\.id \|\| stage\?\.ID/);
  assert.match(appJs, /if \(statusId\.includes\(":"\)\) return statusId/);
  assert.match(appJs, /DT31_\$\{match\[1\]\}:\$\{statusId\}/);
  assert.match(appJs, /function statusStageCode/);
  assert.match(appJs, /function invoiceStageName/);
  assert.match(appJs, /function invoiceAssignedName/);
  assert.match(appJs, /String\(user\.ID \|\| user\.id\)/);
  assert.match(appJs, /loadUsers\(invoices\.map\(invoiceAssignedById\)\)/);
  assert.match(appJs, /invoiceStageName\(invoice\)/);
  assert.match(appJs, /invoiceAssignedName\(invoice\)/);
  assert.match(appJs, /dealAmount,/);
  assert.match(appJs, /function renderDealTitle/);
  assert.match(appJs, /dealTitle\.append\(`В сделке с ID \$\{dealId\} `/);
  assert.match(appJs, /dealLink\.textContent = deal\.TITLE \|\| "без названия"/);
  assert.match(appJs, /закреплена сумма \$\{moneyFormat\.format\(summary\.dealAmount \|\| 0\)\}/);
  assert.match(appJs, /<span>Счёт<\/span>[\s\S]*<span>Срок оплаты<\/span>[\s\S]*<span>Ответственный<\/span>[\s\S]*<span>Сумма<\/span>[\s\S]*<span>Стадия<\/span>[\s\S]*<span>Дата выставления<\/span>/);
  assert.match(appJs, /row\.append\(title, datePay, assignee, amount, stage, dateIssued\)/);
});

test("marketplace report formats invoice dates without time", () => {
  assert.match(appJs, /function formatDateOnly/);
  assert.match(appJs, /return `\$\{isoDate\[3\]\}\.\$\{isoDate\[2\]\}\.\$\{isoDate\[1\]\}`/);
  assert.match(appJs, /invoiceIssuedAt\(invoice\)/);
  assert.match(appJs, /invoiceDeadline\(invoice\)/);
});

test("marketplace automation panel presents mass recalculation and statistics", () => {
  assert.doesNotMatch(indexHtml, /<option value="manual"/);
  assert.match(indexHtml, /Массовый пересчёт сделок/);
  assert.match(indexHtml, /Авторасчёт при изменении сделок\/счетов включён!/);
  assert.match(indexHtml, /class="mapping-auto-note"/);
  assert.doesNotMatch(indexHtml, /<p class="automation-note">Авторасчёт при изменении включён<\/p>/);
  assert.match(indexHtml, /Период расчёта/);
  assert.match(indexHtml, /<option value="onOpen" selected>При открытии сделки<\/option>/);
  assert.match(indexHtml, /<option value="onChange">При изменении сделки\/счёта<\/option>/);
  assert.match(indexHtml, /Утром и вечером/);
  assert.match(indexHtml, /Постоянный/);
  assert.match(indexHtml, /Нужна серверная поддержка/);
  assert.match(indexHtml, /id="automationMode" tabindex="-1"/);
  assert.doesNotMatch(indexHtml, /id="automationSchedule"/);
  assert.doesNotMatch(indexHtml, /<span class="server-only">Интервал<\/span>/);
  assert.match(indexHtml, /<option value="30" selected>1 мес<\/option>/);
  assert.match(indexHtml, /<option value="90">3 мес<\/option>/);
  assert.match(indexHtml, /<option value="180">6 мес<\/option>/);
  assert.doesNotMatch(indexHtml, /21 сутки/);
  assert.doesNotMatch(indexHtml, /42 суток/);
  assert.match(indexHtml, /id="windowSummary" class="window-summary" hidden/);
  assert.match(indexHtml, /id="windowStatsButton"/);
  assert.match(indexHtml, /id="windowStatsModal"/);
  assert.match(indexHtml, /<canvas id="windowStatsChart" class="donut-chart"/);
  assert.match(indexHtml, /id="statsPaidAmount"/);
  assert.match(indexHtml, /id="statsUnpaidAmount"/);
  assert.match(indexHtml, /id="statsEmptyAmount"/);
  assert.match(indexHtml, /id="invoiceAnalyticsTitle"/);
  assert.match(indexHtml, /Статистика сделок за период/);
  assert.match(indexHtml, /Завершено сделок/);
  assert.match(indexHtml, /Сделок ожидают доплаты/);
  assert.match(indexHtml, /Сделок без счетов/);
  assert.doesNotMatch(indexHtml, /legend-error/);
  assert.doesNotMatch(indexHtml, /statsErrorPercent/);
  assert.match(indexHtml, /id="openAppSettings"/);
  assert.match(indexHtml, /aria-label="Настройки приложения"/);
  assert.match(indexHtml, /id="automationCategoryName" class="automation-category"/);
  assert.match(indexHtml, /class="secondary-button icon-button settings-link-button"/);
  assert.match(settingsHtml, /id="calculationCategoryId"/);
  assert.match(settingsHtml, /id="autoRecalcWindowDaysSetting"/);
  assert.match(settingsHtml, /id="windowPeriodHelp"/);
  assert.match(settingsHtml, /id="periodHelpModal"/);
  assert.match(settingsHtml, /DATE_CREATE|дата создания сделки/);
  assert.match(settingsHtml, /Все воронки/);
  assert.match(settingsJs, /crm\.category\.list/);
  assert.match(settingsJs, /dealInvoiceSummaryDealCategories/);
  assert.match(settingsJs, /calculationCategoryId/);
  assert.match(settingsJs, /autoRecalcWindowDays/);
  assert.match(settingsJs, /normalizeWindowDays/);
  assert.match(settingsJs, /dealInvoiceSummaryUserCalculationSettings/);
  assert.match(settingsJs, /function openOpenLineFromSettings/);
  assert.match(settingsJs, /openChat/);
  assert.match(settingsJs, /function showPeriodHelp/);
  assert.match(settingsJs, /localStorage\.setItem\(userCalculationSettingsOption, payload\)/);
  assert.match(settingsJs, /Настройки сохранены для этого пользователя/);
  assert.doesNotMatch(settingsJs, /dealInvoiceSummarySettings: payload/);
  assert.match(settingsJs, /app\.option\.set/);
  assert.match(appJs, /autoRecalcWindowDays:\s*30/);
  assert.match(appJs, /autoRecalcMode:\s*"onOpen"/);
  assert.match(appJs, /onOpen:\s*{[\s\S]*schedule:\s*"при открытии карточки"/);
  assert.match(appJs, /onChange:\s*{[\s\S]*schedule:\s*"при изменении сделки\/счёта"/);
  assert.match(appJs, /interval:\s*"каждые 5 секунд на открытой карточке"/);
  assert.match(appJs, /wake:\s*"не требуется"/);
  assert.match(appJs, /schedule:\s*"в 9:45 утра И в 18:45 вечера"/);
  assert.match(appJs, /сервер включается в 09:45 и 18:45/);
  assert.match(appJs, /Каждый час с 09:00 до 20:00/);
  assert.match(appJs, /сервер просыпается каждый час с 8:30 до 20:30/);
  assert.match(appJs, /каждые 7 мин\.\\nИтого 3 ч 15 мин\/сутки/);
  assert.match(appJs, /Итого 3 ч 15 мин\/сутки, до 200 руб\/мес за 30 рабочих дней/);
  assert.match(appJs, /Итого 30 мин\/сутки, до 145 руб\/мес за 30 рабочих дней/);
  assert.match(indexHtml, /Заявка на серверную версию/);
  assert.match(indexHtml, /windowReportModal/);
  assert.match(indexHtml, /windowConfirmModal/);
  assert.match(indexHtml, /Запускаем расчёт\?/);
  assert.match(indexHtml, />ДА<\/button>/);
  assert.match(indexHtml, />НЕТ<\/button>/);
  assert.match(indexHtml, /class="modal-actions window-report-actions"/);
  assert.match(indexHtml, /id="viewWindowStats"/);
  assert.match(indexHtml, /Посмотреть статистику/);
  assert.match(indexHtml, /downloadWindowReport/);
  assert.doesNotMatch(indexHtml, /loader_9_no7zeu\.js/);
  assert.doesNotMatch(indexHtml, /class="server-only"/);
  assert.match(indexHtml, /class="visually-hidden" type="button" disabled tabindex="-1">Автопересчёт доступен с сервером/);
  assert.match(indexHtml, /Запустить расчёт/);
  assert.doesNotMatch(indexHtml, />Сделать пересчёт всех сделок</);
  assert.match(indexHtml, /id="automationProgress" class="automation-progress" hidden/);
  assert.match(indexHtml, /id="automationElapsed" class="automation-elapsed" hidden/);
  assert.match(appJs, /marketplace-window-recalculate/);
  assert.match(appJs, /operation: "marketplace-window-preflight"/);
  assert.match(appJs, /function recalculateDealsInWindow/);
  assert.match(appJs, /function runWindowCalculation/);
  assert.match(appJs, /function showWindowConfirmModal/);
  assert.match(appJs, /function estimateCalculationSeconds/);
  assert.match(appJs, /Math\.ceil\(\(count \* secondsPerDeal\) \/ 30\) \* 30/);
  assert.match(appJs, /function startAutomationElapsed/);
  assert.match(appJs, /function finishAutomationElapsed/);
  assert.match(appJs, /Время обработки \$\{elapsedText\}/);
  assert.match(appJs, /confirmWindowCalculation\.addEventListener\("click"/);
  assert.match(appJs, /cancelWindowCalculation\.addEventListener\("click"/);
  assert.match(appJs, /saveUserCalculationSettings/);
  assert.match(appJs, /dealInvoiceSummaryUserCalculationSettings/);
  assert.match(appJs, /function getRecentDeals/);
  assert.match(appJs, /getRecentDeals\(days, currentSettings\)/);
  assert.match(appJs, /crm\.deal\.list/);
  assert.match(appJs, /getRecentInvoiceDealIds\(days\)/);
  assert.match(appJs, /recent\.invoiceDealIds = invoiceWindow\.dealIds/);
  assert.match(appJs, /filter:\s*\{ \.\.\.categoryFilter, \[`>=\$\{fieldName\}`\]: since \}/);
  assert.match(appJs, /function downloadWindowReport/);
  assert.match(appJs, /function buildWindowSummary/);
  assert.match(appJs, /function renderWindowSummary/);
  assert.match(appJs, /function resetWindowSummary/);
  assert.match(appJs, /function restoreWindowSummaryForPeriod/);
  assert.match(appJs, /function showWindowStatsModal/);
  assert.match(appJs, /settingsPageFileName = "settings\.html"/);
  assert.match(appJs, /openAppSettingsButton\.addEventListener\("click"/);
  assert.match(appJs, /viewWindowStatsButton\.addEventListener\("click"/);
  assert.doesNotMatch(appJs, /viewWindowStatsButton\.addEventListener\("click", \(\) => \{\s*hideWindowReportModal\(\)/);
  assert.match(appJs, /function renderDealStatusChart/);
  assert.match(appJs, /function drawDealStatusChart/);
  assert.match(appJs, /function updateChartHover/);
  assert.match(appJs, /windowStatsChart\.getContext\("2d"\)/);
  assert.match(appJs, /function dealStageSemantic/);
  assert.match(appJs, /function dealSemanticFromResult/);
  assert.match(appJs, /function windowStatusAmount/);
  assert.match(appJs, /function dealMatchesCalculationCategory/);
  assert.match(appJs, /windowChartState\.slices/);
  assert.match(appJs, /autoRecalcWindowDays\.addEventListener\("change"/);
  assert.match(appJs, /windowStatsChart\.addEventListener\("mousemove", updateChartHover\)/);
  assert.match(appJs, /windowStatsChart\.addEventListener\("mouseleave", clearChartHover\)/);
  assert.match(appJs, /STAGE_SEMANTIC_ID/);
  assert.match(appJs, /acc\.amounts\[group\] \+= windowStatusAmount\(item, group\)/);
  assert.match(appJs, /const dealSemantic = dealSemanticFromResult\(item\)/);
  assert.match(appJs, /if \(!invoiceCount\) group = "empty"/);
  assert.match(appJs, /skippedCategory: Boolean\(result\.skippedCategory\)/);
  assert.match(appJs, /summary\.status\.amounts\.paid/);
  assert.match(appJs, /invoiceAnalyticsTitle\.textContent = `Аналитика счетов за период \$\{windowPeriodLabel\(report\.days\)\}`/);
  assert.doesNotMatch(appJs, /statsErrorPercent/);
  assert.doesNotMatch(appJs, /percentOf/);
  assert.match(appJs, /automationMode\.value = "onChange"/);
  assert.match(appJs, /settings\.autoRecalcMode = "onChange"/);
  assert.doesNotMatch(appJs, /await saveSettings\(defaultSettings\)/);
  assert.doesNotMatch(appJs, /settings\.autoRecalcWindowDays = normalizeWindowDays\(autoRecalcWindowDays\.value\)/);
  assert.doesNotMatch(appJs, /"Ошибки", "Неразрешённые стадии"/);
  assert.doesNotMatch(appJs, /\(item\.stageLookup\?\.unresolved \|\| \[\]\)\.join\(", "\)/);
  assert.match(appJs, /function showWindowReportModal/);
  assert.match(appJs, /function loadServerSupport/);
  assert.match(appJs, /function openOpenLine/);
  assert.match(appJs, /window\.location\.href = marketplaceFileUrl\(settingsPageFileName, \{ openChat: "1" \}\)/);
  assert.match(appJs, /dealInvoiceSummaryServerSupport/);
  assert.match(appJs, /if \(serverSupport\.connected\) return/);
  assert.match(appJs, /const serverOnlyModes = \["continuous", "twiceDaily"\]/);
  assert.match(appJs, /serverOnlyModes\.includes\(automationMode\.value\)/);
  assert.match(appJs, /function renderAutomationModeDetails/);
  assert.match(appJs, /if \(automationSchedule\) automationSchedule\.textContent = details\.schedule/);
  assert.match(appJs, /const writeOnOpen = automationMode\.value === "onOpen"/);
  assert.match(appJs, /await recalculate\(contextDealId, writeOnOpen, \{ refreshCard: writeOnOpen \}\)/);
  assert.match(appJs, /operation: "open-deal-recalculate"/);
  assert.match(appJs, /function buildChangedDealFields/);
  assert.match(appJs, /isBlankCrmValue\(deal\[field\]\) \|\| !sameMoneyValue\(deal\[field\], value\)/);
  assert.match(workerJs, /isBlankCrmValue\(deal\[field\]\) \|\| !sameMoneyValue\(deal\[field\], value\)/);
  assert.match(appJs, /if \(Object\.keys\(fields\)\.length\)/);
  assert.match(appJs, /skippedUpdate = true/);
  assert.match(appJs, /function dealChangeSnapshot/);
  assert.match(appJs, /OPPORTUNITY \?\? deal\.opportunity/);
  assert.match(appJs, /STAGE_ID \|\| deal\.stageId/);
  assert.match(appJs, /function checkContextDealChanges/);
  assert.doesNotMatch(appJs, /document\.hidden\) return/);
  assert.match(appJs, /function getPlacementInterface/);
  assert.match(appJs, /BX24\.placement\.getInterface/);
  assert.match(appJs, /function refreshDealCard/);
  assert.match(appJs, /BX24\.placement\.call\("reloadData"/);
  assert.match(appJs, /cardRefresh: result\.cardRefresh/);
  assert.match(appJs, /BX24\.placement\.bindEvent/);
  assert.match(appJs, /window\.addEventListener\("focus", checkContextDealChanges\)/);
  assert.match(appJs, /document\.addEventListener\("visibilitychange", checkContextDealChanges\)/);
  assert.match(appJs, /setInterval\(checkContextDealChanges, contextDealMonitorIntervalMs\)/);
  assert.match(appJs, /open-deal-change-recalculate/);
  assert.match(appJs, /startContextDealMonitor\(contextDealId, result\.deal\)/);
  assert.match(appJs, /"Остаток оплаты сделки"/);
  assert.match(appJs, /Отчёт сформирован и готов к скачиванию/);
  assert.match(appJs, /if \(reveal && !resultNode\.hidden\) setLogVisible\(true\)/);
  assert.doesNotMatch(appJs, /CSV-отчёт сформирован автоматически/);
  assert.match(appJs, /deal-invoice-window-\$\{source\.days\}-days\.csv/);
  assert.match(appJs, />=\$\{fieldName\}/);
  assert.match(styleCss, /\.setup-grid\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1\.1fr\) minmax\(500px,\s*\.9fr\)/);
  assert.match(styleCss, /\.setup-grid\s*{[\s\S]*align-items:\s*start/);
  assert.match(styleCss, /\.automation-panel:not\(:has\(\.window-summary:not\(\[hidden\]\)\)\)\s*{[\s\S]*align-content:\s*center/);
  assert.match(styleCss, /\.automation-panel:not\(:has\(\.window-summary:not\(\[hidden\]\)\)\) \.automation-title-row/);
  assert.match(styleCss, /\.automation-panel button\s*{[\s\S]*width:\s*100%/);
  assert.match(styleCss, /\.automation-panel \.stats-button\s*{[\s\S]*width:\s*38px/);
  assert.match(styleCss, /\.automation-panel button\s*{[\s\S]*white-space:\s*normal/);
  assert.match(styleCss, /\.automation-list strong\s*{[\s\S]*overflow-wrap:\s*anywhere/);
  assert.match(styleCss, /#automationTracked\s*{[\s\S]*justify-self:\s*start/);
  assert.match(styleCss, /\.automation-title-row/);
  assert.match(styleCss, /\.automation-category/);
  assert.match(styleCss, /\.settings-link-button/);
  assert.match(styleCss, /\.form-actions\s*{[\s\S]*display:\s*grid/);
  assert.match(styleCss, /\.form-actions\s*{[\s\S]*min-height:\s*0/);
  assert.match(styleCss, /\.settings-panel \.form-actions\s*{[\s\S]*grid-template-columns:\s*minmax\(210px,\s*max-content\) minmax\(220px,\s*1fr\)/);
  assert.match(styleCss, /\.settings-panel #settingsStatus\s*{[\s\S]*grid-column:\s*1 \/ -1/);
  assert.match(styleCss, /\.setting-inline-control\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) 34px/);
  assert.match(styleCss, /\.help-button/);
  assert.match(styleCss, /\.settings-help-modal p/);
  assert.match(styleCss, /#mappingStatus\s*{[\s\S]*overflow-wrap:\s*anywhere/);
  assert.match(styleCss, /\.mapping-auto-note/);
  assert.match(styleCss, /\.window-summary/);
  assert.match(styleCss, /\.donut-chart/);
  assert.match(styleCss, /\.stats-deal-count/);
  assert.match(styleCss, /\.invoice-analytics/);
  assert.match(styleCss, /\.window-report-actions\s*{[\s\S]*minmax\(250px,\s*1\.35fr\)/);
  assert.match(styleCss, /\.automation-progress\[data-progress="mid"\]/);
  assert.match(styleCss, /\.automation-progress\[data-progress="high"\]/);
  assert.match(styleCss, /\.automation-progress-track/);
  assert.match(styleCss, /\.automation-elapsed/);
  assert.match(styleCss, /\.modal-backdrop/);
  assert.match(styleCss, /\.modal-panel\s*{[\s\S]*width:\s*min\(640px,\s*100%\)/);
  assert.match(styleCss, /#serverSupportDetails\s*{[\s\S]*margin-top:\s*16px/);
  assert.match(styleCss, /#serverSupportDetails\s*{[\s\S]*white-space:\s*pre-line/);
  assert.doesNotMatch(styleCss, /Georgia/);
});
